// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khiredinofpahnnhquum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoaXJlZGlub2ZwYWhubmhxdXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTk4ODQsImV4cCI6MjA1OTU3NTg4NH0.akvGYdmDDnBJtruFgPX0RAQ0XGv_ZyGFZ8X_AFI5nio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);